### ISSUE TITLE
Error: Could not locate the bindings file. Tried ./node_modules/deasync/build/deasync.node

### ISSUE THREAD

**Issue by snagine** [abbr/deasync#164]
Hi

I am getting the same error.
"deasync": "^0.1.10"
"cypress-testrail-reporter": "^1.3.3"
"cypress-cucumber-preprocessor": "^4.2.0"

I tried uninstalling
npm uninstall deasync
npm install deasync

I still get the error:

The error we received was:

Error: Could not locate the bindings file. Tried:
→ ./node_modules/deasync/build/deasync.node

**Comment by Alterink** [comment]
Hi, 

I have problem with build docker FROM node:16.5-alpine. 
Everything was working two days ago.

I downgrade node to 16.0 and its working.

OS: Ubuntu 18.04.5 LTS


`npm ERR! code 1
npm ERR! path /app/node_modules/deasync
npm ERR! command failed
npm ERR! command sh -c node ./build.js
npm ERR! `linux-x64-node-16` exists; testing
npm ERR! Problem with the binary; manual build incoming
npm ERR! stdout=
npm ERR! err=Error: Command failed: /usr/local/bin/node quick-test.js
npm ERR! /app/node_modules/bindings/bindings.js:135
npm ERR!   throw err;
npm ERR!   ^
npm ERR! 
npm ERR! Error: Could not locate the bindings file. Tried:
npm ERR!  → /app/node_modules/deasync/build/deasync.node
npm ERR!  → /app/node_modules/deasync/build/Debug/deasync.node
npm ERR!  → /app/node_modules/deasync/build/Release/deasync.node
npm ERR!  → /app/node_modules/deasync/out/Debug/deasync.node
npm ERR!  → /app/node_modules/deasync/Debug/deasync.node
npm ERR!  → /app/node_modules/deasync/out/Release/deasync.node
npm ERR!  → /app/node_modules/deasync/Release/deasync.node
npm ERR!  → /app/node_modules/deasync/build/default/deasync.node
npm ERR!  → /app/node_modules/deasync/compiled/16.5.0/linux/x64/deasync.node
npm ERR!  → /app/node_modules/deasync/addon-build/release/install-root/deasync.node
npm ERR!  → /app/node_modules/deasync/addon-build/debug/install-root/deasync.node
npm ERR!  → /app/node_modules/deasync/addon-build/default/install-root/deasync.node
npm ERR!  → /app/node_modules/deasync/lib/binding/node-v93-linux-x64/deasync.node
npm ERR!     at bindings (/app/node_modules/bindings/bindings.js:126:9)
npm ERR!     at Object.<anonymous> (/app/node_modules/deasync/index.js:30:31)
npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1095:14)
npm ERR!     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1124:10)
npm ERR!     at Module.load (node:internal/modules/cjs/loader:975:32)
npm ERR!     at Function.Module._load (node:internal/modules/cjs/loader:816:12)
npm ERR!     at Module.require (node:internal/modules/cjs/loader:999:19)
npm ERR!     at require (node:internal/modules/cjs/helpers:93:18)
npm ERR!     at Object.<anonymous> (/app/node_modules/deasync/quick-test.js:3:13)
npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1095:14) {
npm ERR!   tries: [
npm ERR!     '/app/node_modules/deasync/build/deasync.node',
npm ERR!     '/app/node_modules/deasync/build/Debug/deasync.node',
npm ERR!     '/app/node_modules/deasync/build/Release/deasync.node',
npm ERR!     '/app/node_modules/deasync/out/Debug/deasync.node',
npm ERR!     '/app/node_modules/deasync/Debug/deasync.node',
npm ERR!     '/app/node_modules/deasync/out/Release/deasync.node',
npm ERR!     '/app/node_modules/deasync/Release/deasync.node',
npm ERR!     '/app/node_modules/deasync/build/default/deasync.node',
npm ERR!     '/app/node_modules/deasync/compiled/16.5.0/linux/x64/deasync.node',
npm ERR!     '/app/node_modules/deasync/addon-build/release/install-root/deasync.node',
npm ERR!     '/app/node_modules/deasync/addon-build/debug/install-root/deasync.node',
npm ERR!     '/app/node_modules/deasync/addon-build/default/install-root/deasync.node',
npm ERR!     '/app/node_modules/deasync/lib/binding/node-v93-linux-x64/deasync.node'
npm ERR!   ]
npm ERR! }
`

**Comment by abbr** [comment]
should be fixed with v0.1.26 just published.

**Comment by rjhall90** [comment]
@abbr Still getting errors on v0.1.26.

`Could not locate the bindings file. Tried:  → /node_modules/deasync/build/deasync.node  → /node_modules/deasync/build/Debug/deasync.node  → /node_modules/deasync/build/Release/deasync.node  → /node_modules/deasync/out/Debug/deasync.node  → /node_modules/deasync/Debug/deasync.node  → /node_modules/deasync/out/Release/deasync.node  → /node_modules/deasync/Release/deasync.node  → /node_modules/deasync/build/default/deasync.node  → /node_modules/deasync/compiled/16.13.0/darwin/arm64/deasync.node  → /node_modules/deasync/addon-build/release/install-root/deasync.node  → /node_modules/deasync/addon-build/debug/install-root/deasync.node  → /node_modules/deasync/addon-build/default/install-root/deasync.node  → /node_modules/deasync/lib/binding/node-v101-darwin-arm64/deasync.node`

**Comment by alexnault** [comment]
Also getting this issue with a Macbook Air M2, Node 18.16.0 and deasync 0.1.28.

Running inside a docker container fixes it for me.
